// Package i18n provides type-safe internationalization for Go.
//
// Locale catalogs are loaded from YAML or TOML files at runtime, while
// message constructors are generated by cmd/gen from the default-language
// catalog, so message keys and parameter types are checked at compile time.
package i18n
