package codegen

import (
	"fmt"
	"go/format"
	"go/token"
	"strings"
)

const header = "// Code generated by go-typesafe-i18n; DO NOT EDIT.\n\n"

// importAlias names the runtime package in generated code. buildMessage
// rejects parameters that would shadow it.
const importAlias = "i18n"

// Render generates the Go source of the typed message package for the model.
// The output is deterministic and gofmt-formatted.
func Render(m Model, pkg string) ([]byte, error) {
	if !token.IsIdentifier(pkg) {
		return nil, fmt.Errorf("invalid package name %q", pkg)
	}
	var b strings.Builder
	b.WriteString(header)
	fmt.Fprintf(&b, "package %s\n", pkg)
	if len(m.Messages) > 0 {
		b.WriteString("\nimport (\n\t" + importAlias + " \"github.com/mickamy/go-typesafe-i18n\"\n)\n")
	}
	for _, msg := range m.Messages {
		b.WriteString("\n")
		writeMessage(&b, msg)
	}
	src, err := format.Source([]byte(b.String()))
	if err != nil {
		return nil, fmt.Errorf("format generated code: %w", err)
	}
	return src, nil
}

func writeMessage(b *strings.Builder, msg Message) {
	fmt.Fprintf(b, "// %s returns the %q message.\n", msg.FuncName, msg.Key)
	fmt.Fprintf(b, "func %s(", msg.FuncName)
	for i, p := range msg.Params {
		if i > 0 {
			b.WriteString(", ")
		}
		fmt.Fprintf(b, "%s %s", p.GoName, p.GoType)
	}
	b.WriteString(") i18n.Message {\n")
	if len(msg.Params) == 0 {
		fmt.Fprintf(b, "\treturn i18n.Message{Key: %q}\n}\n", msg.Key)
		return
	}
	fmt.Fprintf(b, "\treturn i18n.Message{Key: %q, Args: []i18n.Arg{\n", msg.Key)
	for _, p := range msg.Params {
		fmt.Fprintf(b, "\t\t{Name: %q, Value: %s},\n", p.Name, p.GoName)
	}
	b.WriteString("\t}}\n}\n")
}
