package codegen

import "text/template"

var codeTemplate = template.Must(template.New("code").Parse(`// Code generated by go-typesafe-i18n; DO NOT EDIT.
package {{.PackageName}}

import "github.com/mickamy/go-typesafe-i18n"

{{range .Messages}}
// {{.FuncName}} returns a Message for "{{.Key}}".
{{- if .IsPlural}}
// Plural forms: {{range $k, $v := .PluralForms}}{{$k}}={{$v}} {{end}}
{{- else}}
// Template: {{.Template}}
{{- end}}
func {{.FuncName}}({{.ParamList}}) i18n.Message {
{{- if .IsPlural}}
	return i18n.Message{
		ID: "{{.Key}}",
{{- if .HasArgs}}
		Args: map[string]any{
{{- range .Placeholders}}
			"{{.Name}}": {{.ParamName}},
{{- end}}
		},
{{- end}}
		PluralCount: &{{.PluralCountParam}},
	}
{{- else if .HasArgs}}
	return i18n.Message{
		ID: "{{.Key}}",
		Args: map[string]any{
{{- range .Placeholders}}
			"{{.Name}}": {{.ParamName}},
{{- end}}
		},
	}
{{- else}}
	return i18n.Message{ID: "{{.Key}}"}
{{- end}}
}
{{end}}
`))
