// Code generated by go-typesafe-i18n; DO NOT EDIT.
package messages

import "github.com/mickamy/go-typesafe-i18n"

// Greeting returns a Message for "greeting".
// Template: Hello
func Greeting() i18n.Message {
	return i18n.Message{ID: "greeting"}
}

// Hello returns a Message for "hello".
// Template: Hello, {name}!
func Hello(name string) i18n.Message {
	return i18n.Message{
		ID: "hello",
		Args: map[string]any{
			"name": name,
		},
	}
}

// ItemsCount returns a Message for "items_count".
// one: You have 1 item
// other: You have {count:int} items
func ItemsCount(count int) i18n.Message {
	return i18n.Message{
		ID: "items_count",
		Args: map[string]any{
			"count": count,
		},
		PluralCount: &count,
	}
}

// TotalPrice returns a Message for "total_price".
// Template: Total: ${price:float}
func TotalPrice(price float64) i18n.Message {
	return i18n.Message{
		ID: "total_price",
		Args: map[string]any{
			"price": price,
		},
	}
}

// UserDeleted returns a Message for "user.deleted".
// Template: User {name} has been deleted
func UserDeleted(name string) i18n.Message {
	return i18n.Message{
		ID: "user.deleted",
		Args: map[string]any{
			"name": name,
		},
	}
}

// UserNotFound returns a Message for "user.not_found".
// Template: User not found
func UserNotFound() i18n.Message {
	return i18n.Message{ID: "user.not_found"}
}
