// Code generated by go-typesafe-i18n; DO NOT EDIT.

package messages

import (
	i18n "github.com/mickamy/go-typesafe-i18n"
)

// Greeting returns the "greeting" message.
func Greeting() i18n.Message {
	return i18n.Message{Key: "greeting"}
}

// Hello returns the "hello" message.
func Hello(name string) i18n.Message {
	return i18n.Message{Key: "hello", Args: []i18n.Arg{
		{Name: "name", Value: name},
	}}
}

// ItemsCount returns the "items_count" message.
func ItemsCount(count int) i18n.Message {
	return i18n.Message{Key: "items_count", Args: []i18n.Arg{
		{Name: "count", Value: count},
	}}
}

// TotalPrice returns the "total_price" message.
func TotalPrice(price float64) i18n.Message {
	return i18n.Message{Key: "total_price", Args: []i18n.Arg{
		{Name: "price", Value: price},
	}}
}

// UserDeleted returns the "user.deleted" message.
func UserDeleted(name string) i18n.Message {
	return i18n.Message{Key: "user.deleted", Args: []i18n.Arg{
		{Name: "name", Value: name},
	}}
}

// UserNotFound returns the "user.not_found" message.
func UserNotFound() i18n.Message {
	return i18n.Message{Key: "user.not_found"}
}
